name: lint

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Run pre-commit as linter
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files --show-diff-on-failure
