name: Lint and Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Lint and Test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8 environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pre-commit as linter
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
      - name: Test with pytest
        run: |
          pytest -q tests/
